In [1]:
from tensorflow.keras.preprocessing.text import one_hot

## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [2]:
### sentences
sent=[  'Hima eats mango',
      'mango on tree',
      'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good girl',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
vocab_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,vocab_size)for words in sent]
one_hot_repr

[[8878, 8609, 4971],
 [4971, 3892, 5106],
 [1017, 2398, 6372, 862],
 [1017, 2398, 6372, 5608],
 [1017, 5016, 6372, 9744],
 [1386, 6734, 7133, 4204, 1733],
 [1386, 6734, 7133, 4204, 8320],
 [9914, 1017, 3761, 6372, 6593],
 [632, 4123, 2363, 4204]]

In [5]:
sent_length=9

embedded_docs= pad_sequences(one_hot_repr, padding='post', maxlen=sent_length)
print(embedded_docs)

[[8878 8609 4971    0    0    0    0    0    0]
 [4971 3892 5106    0    0    0    0    0    0]
 [1017 2398 6372  862    0    0    0    0    0]
 [1017 2398 6372 5608    0    0    0    0    0]
 [1017 5016 6372 9744    0    0    0    0    0]
 [1386 6734 7133 4204 1733    0    0    0    0]
 [1386 6734 7133 4204 8320    0    0    0    0]
 [9914 1017 3761 6372 6593    0    0    0    0]
 [ 632 4123 2363 4204    0    0    0    0    0]]


In [6]:
dim=10

In [7]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

/Users/himas1/Documents/Projects/rnn-imdb/venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[[ 0.04171612,  0.00028818, -0.0141392 , -0.03235834,
          0.03890529,  0.02598821,  0.01930432, -0.00707565,
          0.01786796, -0.00425123],
        [-0.01498439, -0.00849136, -0.0027901 ,  0.02118598,
         -0.03463601, -0.03955961,  0.00621895, -0.00794675,
          0.0305093 , -0.01305298],
        [ 0.0271014 ,  0.01520855, -0.03851253,  0.04835087,
         -0.01853924, -0.01861648, -0.04631889,  0.02304459,
          0.01175356,  0.01139265],
        [ 0.03507501,  0.03471697,  0.03398244, -0.03698543,
          0.04929403, -0.02619829,  0.01876798,  0.02735702,
          0.04574079,  0.03851553],
        [ 0.03507501,  0.03471697,  0.03398244, -0.03698543,
          0.04929403, -0.02619829,  0.01876798,  0.02735702,
          0.04574079,  0.03851553],
        [ 0.03507501,  0.03471697,  0.03398244, -0.03698543,
          0.04929403, -0.02619829,  0.01876798,  0.02735702,
          0.04574079,  0.03851553],
        [ 0.03507501,  0.03471697,  0.03398244, -0.0

In [10]:
embedded_docs[0]

array([8878, 8609, 4971,    0,    0,    0,    0,    0,    0], dtype=int32)

In [12]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[[ 0.04171612,  0.00028818, -0.0141392 , -0.03235834,
          0.03890529,  0.02598821,  0.01930432, -0.00707565,
          0.01786796, -0.00425123],
        [-0.01498439, -0.00849136, -0.0027901 ,  0.02118598,
         -0.03463601, -0.03955961,  0.00621895, -0.00794675,
          0.0305093 , -0.01305298],
        [ 0.0271014 ,  0.01520855, -0.03851253,  0.04835087,
         -0.01853924, -0.01861648, -0.04631889,  0.02304459,
          0.01175356,  0.01139265],
        [ 0.03507501,  0.03471697,  0.03398244, -0.03698543,
          0.04929403, -0.02619829,  0.01876798,  0.02735702,
          0.04574079,  0.03851553],
        [ 0.03507501,  0.03471697,  0.03398244, -0.03698543,
          0.04929403, -0.02619829,  0.01876798,  0.02735702,
          0.04574079,  0.03851553],
        [ 0.03507501,  0.03471697,  0.03398244, -0.03698543,
          0.04929403, -0.02619829,  0.01876798,  0.02735702,
          0.04574079,  0.03851553],
        [ 0.03507501,  0.03471697,  0.03398244, -0.0